#!/usr/bin/env zsh
echo "Updating versions on local dev ports..."
update_port_versions.sh
port selfupdate && \
port outdated > ~/playground/port_outdated.txt && \
cat ~/playground/port_outdated.txt && sleep 1
port upgrade outdated &&\
port -f uninstall inactive && \
port clean --all installed;
port installed > ~/playground/port_installed.txt;
growlnotify -n port -s -p 2 -m 'Macport update has finished.'
echo "Ports updated:"
cat ~/playground/port_outdated.txt | sed -e 's/are outdated/were updated/' -e 's/</->/'
livecheckport
