#!/usr/bin/env bash
export LANG=C
sudo port selfupdate \
&& port outdated | tee ~/playground/port_outdated.txt \
sudo port upgrade outdated
printf '\a'
sudo port upgrade outdated
port installed > ~/Documents/Source/playground/port_installed.txt
port installed requested > ~/Documents/Source/playground/port_installed_requested.txt
sudo echo "Updating versions on local dev ports..."
update_port_versions.sh
livecheckport
